### ISSUE TITLE
Roadmap v1.0

### ISSUE THREAD

**Issue by TrixiEther** [TrixiEther/lsb-steganography-java#1]
- [ ] Creating an image with hidden text
- [ ] Decoding an image with hidden text
- [ ] Creating an image with a hidden container image
- [ ] Decoding an image with a hidden container image
- [ ] Cryptography support for encoding text
- [ ] Cryptography support for encoding images
- [ ] Cryptography support for decoding text
- [ ] Cryptography support for decoding images
